name: wow_companion
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Routing
  go_router: ^14.6.2

  # Dependency Injection
  get_it: ^8.0.2

  # Network
  dio: ^5.7.0

  # UI
  google_fonts: ^6.2.1

  # Utils
  dartz: ^0.10.1

  # Local Storage
  shared_preferences: ^2.3.4

  # Images
  cached_network_image: ^3.4.1

  # Browser
  url_launcher: ^6.3.1

  logger: ^2.5.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true


